# Generated by Django 5.2.8 on 2025-11-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock", models.IntegerField(default=0)),
                ("category", models.CharField(max_length=100)),
                ("image_url", models.URLField(blank=True, default="")),
            ],
            options={
                "verbose_name_plural": "candies",
                "ordering": ["name"],
            },
        ),
    ]
