# Generated by Django 6.0 on 2025-12-08 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_order_orderitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="candy",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
