# Generated by Django 6.0 on 2025-12-23 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_id",
            field=models.CharField(
                blank=True, editable=False, max_length=5, null=True, unique=True
            ),
        ),
    ]
